name: CI-dev

on:
    push:
        branches: [develop]
    pull_request:
        branches: [develop]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2
        - name: running develop ci
          with:
	      command: ls -a
              host: ${{ secrets.HOST }}
	      username: fred
	      passphrase: ${{ secrets.PASSPHRASE }}
	      privateKey: ${{ secrets.PRIVATE_KEY }}
