name: CI-dev

on:
    push:
        branches: [develop]
    pull_request:
        branches: [develop]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: running develop ci
          uses: actions/checkout@v2
          with:
              command: ls -a
              host: ${{ secrets.HOST }}
              username: fred
              passphrase: ${{ secrets.PASSPHRASE }}
              privateKey: ${{ secrets.PRIVATE_KEY }}
