name: CI-dev

on:
    push:
        branches: [develop]
    pull_request:
        branches: [develop]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: running develop ci
          uses: appleboy/ssh-action@master
          with:
              script: whoami
              host: ${{ secrets.HOST }}
              username: fred
              passphrase: ${{ secrets.PASSPHRASE }}
              privateKey: ${{ secrets.PRIVATE_KEY }}
              port: 22
