name: CI-dev

on:
    push:
        branches: [develop]
    pull_request:
        branches: [develop]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: clean all
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST }}
            username: fred
            password: ${{ secrets.PASSWORD }}
            port: 22
            script: ./deploy-scripts/natashkola/clean-all.sh
        - name: clone
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST }}
            username: fred
            password: ${{ secrets.PASSWORD }}
            port: 22
            script: ./deploy-scripts/natashkola/clone.sh
        - name: pulldev
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST }}
            username: fred
            password: ${{ secrets.PASSWORD }}
            port: 22
            script: ./deploy-scripts/natashkola/pulldev.sh
        - name: build
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST }}
            username: fred
            password: ${{ secrets.PASSWORD }}
            port: 22
            script: ./deploy-scripts/natashkola/build.sh
        - name: dockerize
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST }}
            username: fred
            password: ${{ secrets.PASSWORD }}
            port: 22
            script: ./deploy-scripts/natashkola/dockerize.sh





